### import libraries

In [85]:
import numpy as np, time
import pandas as pd 
from faker import Faker as fk 
import matplotlib.pyplot as plt
fake = fk("fa_IR")
number_of_employees = 400

### Basic personal information

In [86]:
# national_code = 03 + 7/8 + 7 ranom number
d = pd.DataFrame({
    "n1": "03",
    "n2": np.random.choice([7, 8], size = number_of_employees).astype(str),
    "n3": np.random.randint(1000000, 10000000, size = number_of_employees).astype(str)
})

d["national_code"] = d["n1"] + d["n2"] + d["n3"]
d = d.drop(["n1", "n2", "n3"], axis=1)

# phone number = 09 + 9 random number
d["n1"] = "09"
d["n2"] = np.random.choice(["12", "19", "10"], size = number_of_employees)
d["n3"] = np.random.randint(1000000, 10000000, size = number_of_employees).astype(str)
d["phone_number"] = d["n1"] + d["n2"] + d["n3"]
d = d.drop(["n1", "n2", "n3"], axis=1)

# emergency contact   phone + name
d["n1"] = "09"
d["n2"] = np.random.choice(["12", "19", "10"], size = number_of_employees)
d["n3"] = np.random.randint(1000000, 10000000, size = number_of_employees).astype(str)
d_ecn = [{
    "emergency_contact_name": fake.name()
}
    for _ in range(number_of_employees)]
d["emergency_contact_phone"] = d["n1"] + d["n2"] + d["n3"]
d = d.drop(["n1", "n2", "n3"], axis=1)
    
d_1 = pd.DataFrame(d_ecn)
d = pd.concat([d, d_1], axis=1)

In [87]:
# first name
# last name
# father name
# gender
d_f = [{
    "first_name": fake.first_name_female(),
    "last_name": fake.last_name(),
    "gender": "خانم",
    "father_name": fake.first_name_male(),
    "email": fake.company_email()
}
    for _ in range(int(number_of_employees * 0.35))]
d_m = [{
    "first_name": fake.first_name_male(),
    "last_name": fake.last_name(),
    "gender": "آقا",
    "father_name": fake.first_name_male(),
    "email": fake.company_email()
}
    for _ in range(int(number_of_employees * 0.65))]
d_s = d_f + d_m
d_s = pd.DataFrame(d_s)
d = pd.concat([d, d_s], axis=1)

In [88]:
# birth date
dates = pd.date_range('1960-01-01', '2008-01-01', freq=' D')
birth_date = np.random.choice(dates, size= number_of_employees, replace= True)
d_s = pd.DataFrame(birth_date)
d = pd.concat([d, d_s], axis=1)

# marital status
today = pd.Timestamp.today()
marital_status = []
for a in birth_date:
    a = (today - a).days // 365
    if a <= 22:
        marital_status.append(np.random.choice(["مجرد", "متاهل"], p= [0.95, 0.05]))
    elif a <= 27:
        marital_status.append(np.random.choice(["مجرد", "متاهل"], p= [0.6, 0.4]))
    elif a <= 35:
        marital_status.append(np.random.choice(["مجرد", "متاهل"], p= [0.3, 0.7]))
    elif a <= 50:
        marital_status.append(np.random.choice(["مجرد", "متاهل"], p= [0.15, 0.85]))
    else:
        marital_status.append(np.random.choice(["مجرد", "متاهل"], p= [0.1, 0.9]))
        
marital_status = pd.DataFrame(marital_status)
d["marital_status"] = marital_status
d.rename(columns= { 0: "birth_date"}, inplace=True)

In [89]:
# address
d_s = [{
    "address": fake.street_address(),
}
    for _ in range(number_of_employees)]
d["address"] = pd.DataFrame(d_s)

In [90]:
# Job group
job_group_kind = ["وکلا و مشاوران حقوقی", "پشتیبانی حقوقی", "ستادی", "مدیران"]
d["job_group"] = np.random.choice(job_group_kind, size= number_of_employees, p= [0.45, 0.2, 0.2, 0.15])


# field of study
field = []
for a in d["job_group"]:
    if a == "وکلا و مشاوران حقوقی":
        field.append(np.random.choice(["حقوق خصوصی", "حقوق عمومی", "حقوق تجارت", "حقوق بین‌الملل", "حقوق کیفری"]))
    elif a == "پشتیبانی حقوقی":
        field.append(np.random.choice(["حقوق", "مدیریت", "علوم اداری", "حقوق خصوصی"]))
    elif a == "ستادی":
        field.append(np.random.choice(["مدیریت", "حسابداری", "مهندسی کامپیوتر", "مدیریت منابع انسانی", "روابط عمومی"]))
    else:
        field.append(np.random.choice(["حقوق", "MBA", "مدیریت", "حقوق تجارت"]))
        
d["field_of_study"] = field


# education level
education_level = []
for i in range(len(d)):
    b = d["job_group"].iloc[i]
    a = (today - d["birth_date"].iloc[i]).days // 365
    if a >= 35:
        if b == "وکلا و مشاوران حقوقی":
            education_level.append(np.random.choice(["دکتری", "کارشناسی ارشد", "کارشناسی"], p= [0.3, 0.65, 0.05]))
        elif b == "پشتیبانی حقوقی":
            education_level.append(np.random.choice(["دکتری", "کارشناسی ارشد", "کارشناسی"], p= [0.2, 0.5, 0.3]))
        elif b == "ستادی":
            education_level.append(np.random.choice(["دکتری", "کارشناسی ارشد", "کارشناسی"], p= [0.25, 0.45, 0.3]))
        else:
            education_level.append(np.random.choice(["دکتری", "کارشناسی ارشد", "کارشناسی"], p= [0.4, 0.5, 0.1]))
    elif (a < 35) & (a >= 27):
        if b == "وکلا و مشاوران حقوقی":
            education_level.append(np.random.choice(["دکتری", "کارشناسی ارشد", "کارشناسی"], p= [0.3, 0.6, 0.1]))
        elif b == "پشتیبانی حقوقی":
            education_level.append(np.random.choice(["کارشناسی ارشد", "کارشناسی"], p= [0.3, 0.7]))
        elif b == "ستادی":
            education_level.append(np.random.choice(["دکتری", "کارشناسی ارشد", "کارشناسی"], p= [0.15, 0.35, 0.5]))
        else:
            education_level.append(np.random.choice(["دکتری", "کارشناسی ارشد", "کارشناسی"], p= [0.3, 0.5, 0.2]))
    elif (a < 27) & (a >= 24):
        if b == "وکلا و مشاوران حقوقی":
            education_level.append(np.random.choice(["دکتری", "کارشناسی ارشد", "کارشناسی"], p= [0.0, 0.7, 0.3]))
        elif b == "پشتیبانی حقوقی":
            education_level.append(np.random.choice(["کارشناسی ارشد", "کارشناسی"], p= [0.3, 0.7]))
        elif b == "ستادی":
            education_level.append(np.random.choice(["کارشناسی ارشد", "کارشناسی"], p= [0.35, 0.65]))
        else:
            education_level.append(np.random.choice(["دکتری", "کارشناسی ارشد", "کارشناسی"], p= [0.0, 0.7, 0.3]))
    else:
        if b == "وکلا و مشاوران حقوقی":
            education_level.append(np.random.choice(["کارشناسی ارشد", "کارشناسی"], p= [0.1, 0.9]))
        elif b == "پشتیبانی حقوقی":
            education_level.append(np.random.choice(["کارشناسی ارشد", "کارشناسی"], p= [0.05, 0.95]))
        elif b == "ستادی":
            education_level.append(np.random.choice(["کارشناسی ارشد", "کارشناسی"], p= [0.21, 0.79]))
        else:
            education_level.append(np.random.choice(["کارشناسی ارشد", "کارشناسی"], p= [0.2, 0.8]))

d["education_level"] = education_level

# university
uni_kind = ["sorbonne", "UCL", "امیرکبیر", "شریف", "تهران", "manchester", "شهید بهشتی", "علامه", "شیراز", "الزهرا", "آزاد"]
university = []
for i in range(len(d)):
    if d["education_level"].iloc[i] == "دکتری":
        university.append(np.random.choice(uni_kind)) 
    elif d["education_level"].iloc[i] == "کارشناسی ارشد":
        university.append(np.random.choice(uni_kind))
    else:
        university.append(np.random.choice(uni_kind))
d["university"] = university

In [91]:
# position
position = []
for i in range(len(d)):
    if d["job_group"].iloc[i] == "وکلا و مشاوران حقوقی":
        if d["education_level"].iloc[i] == "کارشناسی":
            position.append("وکیل پایه")
        elif d["education_level"].iloc[i] == "کارشناسی ارشد":
            position.append(np.random.choice(["مشاور حقوقی", "کارشناس قرارداد ارشد"], p= [0.4, 0.6]))
        else:
            position.append(np.random.choice(["وکیل ارشد", "وکیل متخصص", "مشاور حقوقی ارشد"], p= [0.45, 0.3, 0.25]))
            
    elif d["job_group"].iloc[i] == "پشتیبانی حقوقی":
        if d["education_level"].iloc[i] == "کارشناسی":
            position.append(np.random.choice(["کارشناس اداری حقوقی", "کارشناس اسناد"], p= [0.5, 0.5]))
        elif d["education_level"].iloc[i] == "کارشناسی ارشد":
            position.append(np.random.choice(["کارشناس اسناد ارشد", "تحلیلگر قرارداد ارشد"], p= [0.4, 0.6]))
        else:
            position.append(np.random.choice(["مدیر پژوهش حقوقی", "تحلیلگر حقوقی ارشد", "مشاور اسناد ارشد"], p= [0.4, 0.35, 0.25]))
            
    elif d["job_group"].iloc[i] == "ستادی":
        if d["education_level"].iloc[i] == "کارشناسی":
            if d["field_of_study"].iloc[i] == "مدیریت منابع انسانی":
                position.append("کارشناس منابع انسانی")
            elif d["field_of_study"].iloc[i] == "روابط عمومی":
                position.append("کارشناس روابط عمومی")
            elif d["field_of_study"].iloc[i] == "مهندسی کامپیوتر":
                position.append("کارشناس IT")
            elif d["field_of_study"].iloc[i] == "حسابداری":
                position.append("کارشناس مالی")
            else:
                position.append("کارشناس اداری")
        else:
            if d["field_of_study"].iloc[i] == "مدیریت منابع انسانی":
                position.append("کارشناس منابع انسانی ارشد")
            elif d["field_of_study"].iloc[i] == "روابط عمومی":
                position.append("کارشناس روابط عمومی ارشد")
            elif d["field_of_study"].iloc[i] == "مهندسی کامپیوتر":
                position.append("کارشناس IT ارشد")
            elif d["field_of_study"].iloc[i] == "حسابداری":
                position.append("کارشناس مالی ارشد")
            else:
                position.append("کارشناس اداری ارشد")
    else:
        if d["education_level"].iloc[i] == "کارشناسی":
            position.append(np.random.choice(["مدیر IT", "مدیر مالی", "مدیر اداری"], p=[0.3, 0.35, 0.35]))
        elif d["education_level"].iloc[i] == "کارشناسی ارشد":
            position.append(np.random.choice(["مدیر منابع انسانی", "مدیر عملیات", "مدیر روابط عمومی"], p=[0.35, 0.35, 0.3]))
        else:
            position.append(np.random.choice(["مدیر واحد حقوقی", "مدیر ارشد عملیات", "معاون مدیریت"], p=[0.4, 0.35, 0.25]))
d["position"] = position

In [92]:
# hire date
hire_date = []
for i in range(len(d)):
    if d["education_level"].iloc[i] == "دکتری":
        min_year = pd.to_timedelta(9900, unit='D')
    elif d["education_level"].iloc[i] == "کارشناسی ارشد":
        min_year = pd.to_timedelta(8800, unit='D')
    else:
        min_year = pd.to_timedelta(8100, unit='D')
        
    min_date = d["birth_date"].iloc[i] + min_year
    
    end_date = pd.Timestamp('2026-01-01')
    if min_date >= end_date:
        min_date = end_date - pd.to_timedelta(365, unit='D')

    hire_date_s = np.random.choice(pd.date_range(min_date, end_date, freq='D'))
    hire_date.append(hire_date_s)

d["hire_date"] = hire_date
d["hire_date"].notna().count()

np.int64(400)

In [93]:
# employment status 
emplloyment_status_kind = ["فعال", "استعفا", "اخراج", "تعلیق"]
employment_status = np.random.choice(emplloyment_status_kind, size=number_of_employees, p=[0.85, 0.07, 0.03, 0.05])
d["employment_status"] = employment_status

In [94]:
# employee id
d["employee_id"] = "EMP" + (np.random.choice(np.arange(1000, 10000), size=number_of_employees, replace=False)).astype(str)

In [95]:
# department
department = []
dept_map = {
    "وکلا و مشاوران حقوقی": {
        "دپارتمان حقوقی قراردادها": 0.45,
        "مشاوره حقوقی شرکتی":      0.55,
    },
    "پشتیبانی حقوقی": {
        "دپارتمان اسناد و مدارک":    0.65,
        "دپارتمان تحقیقات حقوقی":   0.35,
    },
    "ستادی": {
        "اداری و پشتیبانی":   0.35,
        "مالی و حسابداری":    0.30,
        "فناوری اطلاعات":     0.20,
        "منابع انسانی":       0.15,
    },
    "مدیران": {
        "مدیریت ارشد": 1.0,
    },
}
position_dept_affinity = {
    "کارشناس IT":           "فناوری اطلاعات",
    "کارشناس IT ارشد":      "فناوری اطلاعات",
    "مدیر IT":              "فناوری اطلاعات",
    "کارشناس مالی":         "مالی و حسابداری",
    "کارشناس مالی ارشد":    "مالی و حسابداری",
    "مدیر مالی":            "مالی و حسابداری",
    "کارشناس منابع انسانی":       "منابع انسانی",
    "کارشناس منابع انسانی ارشد":  "منابع انسانی",
    "مدیر منابع انسانی":          "منابع انسانی",
    "کارشناس اسناد":              "دپارتمان اسناد و مدارک",
    "کارشناس اسناد ارشد":         "دپارتمان اسناد و مدارک",
    "مشاور اسناد ارشد":           "دپارتمان اسناد و مدارک",
    "مدیر پژوهش حقوقی":           "دپارتمان تحقیقات حقوقی",
    "تحلیلگر حقوقی ارشد":         "دپارتمان تحقیقات حقوقی",
    "تحلیلگر قرارداد ارشد":       "دپارتمان حقوقی قراردادها",
    "کارشناس قرارداد ارشد":       "دپارتمان حقوقی قراردادها",
    "وکیل پایه":                  None,  # تصادفی از گروه خودش
    "وکیل ارشد":                  None,
    "وکیل متخصص":                 None,
    "مشاور حقوقی":                "مشاوره حقوقی شرکتی",
    "مشاور حقوقی ارشد":           "مشاوره حقوقی شرکتی",
    "مدیر واحد حقوقی":            "مدیریت ارشد",
    "مدیر ارشد عملیات":           "مدیریت ارشد",
    "معاون مدیریت":               "مدیریت ارشد",
    "مدیر عملیات":                "مدیریت ارشد",
    "مدیر روابط عمومی":           "مدیریت ارشد",
    "مدیر اداری":                 "اداری و پشتیبانی",
    "کارشناس اداری":              "اداری و پشتیبانی",
    "کارشناس اداری ارشد":         "اداری و پشتیبانی",
    "کارشناس اداری حقوقی":        "اداری و پشتیبانی",
    "کارشناس روابط عمومی":        "اداری و پشتیبانی",
    "کارشناس روابط عمومی ارشد":   "اداری و پشتیبانی",
}
for i in range(len(d)):
    dep_s = position_dept_affinity.get(d["position"].iloc[i])
    if dep_s:
        department.append(dep_s)
    else:
        department.append(np.random.choice(list(dept_map[d["job_group"].iloc[i]].keys()), p=list(dept_map[d["job_group"].iloc[i]].values())))
d["department"] = pd.DataFrame(department)

In [96]:
# CEO
# manager_id = "EMP0000"
ceo_dic = {
    "national_code": "0362528876",
    "phone_number": "091277594481",
    "emergency_contact_phone": "09960857522",
    "emergency_contact_name": "منا محمدی",
    "first_name": "مریم",
    "last_name": "امینی خواه",
    "gender": "خانم",
    "father_name": "حسن",
    "email": "amaryam6674@gmail.com",
    "birth_date": "1982-07-29 00:00:00",
    "marital_status": "مجرد",
    "address": "80143 آوا کوچه واحد 560",
    "job_group": "مدیران",
    "field_of_study": "MBA",
    "education_level": "دکتری",
    "university": "IESE",
    "position": "CEO",
    "hire_date": "2002-07-29 00:00:00",
    "employment_status": "فعال",
    "employee_id": "EMP0000",
    "department": "مدیریت ارشد"
}
d = pd.concat([d, pd.DataFrame([ceo_dic])], ignore_index=True)

In [97]:
# manager id found
manager_positions = {
    "مدیر IT", "مدیر مالی", "مدیر منابع انسانی", "مدیر اداری",
    "مدیر پژوهش حقوقی", "مدیر واحد حقوقی", "مدیر ارشد عملیات",
    "مدیر عملیات", "مدیر روابط عمومی", "معاون مدیریت",
    "مشاور اسناد ارشد", "تحلیلگر قرارداد ارشد", "CEO", "وکیل متخصص"
}

mask = (d["employment_status"] == "فعال") & (d["position"].isin(manager_positions))
manager_id_d = d[mask][["position", "department"]].copy()
manager_id_d.index.name = "index"
manager_id_d = manager_id_d.reset_index()

manager_id_d

    index              position                department
0       1          معاون مدیریت               مدیریت ارشد
1       8             مدیر مالی           مالی و حسابداری
2      15           مدیر عملیات               مدیریت ارشد
3      21     مدیر منابع انسانی              منابع انسانی
4      22  تحلیلگر قرارداد ارشد  دپارتمان حقوقی قراردادها
..    ...                   ...                       ...
83    381       مدیر واحد حقوقی               مدیریت ارشد
84    394  تحلیلگر قرارداد ارشد  دپارتمان حقوقی قراردادها
85    395  تحلیلگر قرارداد ارشد  دپارتمان حقوقی قراردادها
86    398            وکیل متخصص  دپارتمان حقوقی قراردادها
87    400                   CEO               مدیریت ارشد

[88 rows x 3 columns]

In [ ]:
# manager id assign
hierarchy = {
    # dept_name : (positions_of_employees_in_this_dept, positions_of_their_managers)
    "فناوری اطلاعات":           (["کارشناس IT", "کارشناس IT ارشد"],
                                ["مدیر IT"]),
    "مالی و حسابداری":          (["کارشناس مالی", "کارشناس مالی ارشد"],
                                ["مدیر مالی"]),
    "منابع انسانی":             (["کارشناس منابع انسانی", "کارشناس منابع انسانی ارشد"],
                                ["مدیر منابع انسانی"]),
    "اداری و پشتیبانی":         (["کارشناس اداری", "کارشناس اداری ارشد","کارشناس اداری حقوقی", "کارشناس روابط عمومی","کارشناس روابط عمومی ارشد"],
                                ["مدیر اداری"]),
    "دپارتمان اسناد و مدارک":   (["کارشناس اسناد", "کارشناس اسناد ارشد"],
                                ["مشاور اسناد ارشد"]),
    "دپارتمان تحقیقات حقوقی":   (["تحلیلگر حقوقی ارشد"],
                                ["مدیر پژوهش حقوقی"]),
    "دپارتمان حقوقی قراردادها": (["وکیل پایه", "وکیل ارشد", "کارشناس قرارداد ارشد","مشاور حقوقی"],
                                ["تحلیلگر قرارداد ارشد"]),
    "مشاوره حقوقی شرکتی":       (["وکیل پایه", "وکیل ارشد", "مشاور حقوقی","مشاور حقوقی ارشد"],
                                ["وکیل متخصص"]),
    "مدیریت ارشد":              (["مدیر IT", "مدیر مالی", "مدیر منابع انسانی", "مدیر اداری","مشاور اسناد ارشد", "مدیر پژوهش حقوقی","تحلیلگر قرارداد ارشد", "وکیل متخصص","مدیر واحد حقوقی", "مدیر عملیات", "مدیر روابط عمومی"],
                                ["مدیر ارشد عملیات", "معاون مدیریت"]),
}

active = d["employment_status"] == "فعال"
d["manager_id"] = pd.NA
d["manager_id"] = d["manager_id"].astype("Int64")

ceo_idx = d[d["position"] == "CEO"].index[0]

for dept, (emp_pos, mgr_pos) in hierarchy.items():
    mgr_idx = d[active & d["position"].isin(mgr_pos) & (d["department"] == dept)].index.tolist()
    emp_idx = d[active & d["position"].isin(emp_pos) & (d["department"] == dept)
                & ~d.index.isin(mgr_idx)].index.tolist()

    if not emp_idx:
        continue
    if not mgr_idx:
        raise ValueError(f"'{dept}' کارمند دارد ولی مدیر فعال ندارد.")
    if len(mgr_idx) > len(emp_idx):
        raise ValueError(f"'{dept}': مدیران ({len(mgr_idx)}) از کارکنان ({len(emp_idx)}) بیشترند.")

    for i, eidx in enumerate(emp_idx):
        d.at[eidx, "manager_id"] = mgr_idx[i % len(mgr_idx)]

senior_idx = d[active & d["position"].isin(["مدیر ارشد عملیات", "معاون مدیریت"])].index.tolist()
for idx in senior_idx:
    d.at[idx, "manager_id"] = ceo_idx

d

,national_code,phone_number,emergency_contact_phone,emergency_contact_name,first_name,last_name,gender,father_name,email,birth_date,...,job_group,field_of_study,education_level,university,position,hire_date,employment_status,employee_id,department,manager_id
0,0372686217,09101612060,09103405460,سرکار خانم دکتر ستایش مهدیان,حنانه,تحسینی,خانم,احسان,mhmd42@grwh.ir,2006-10-21 00:00:00,...,وکلا و مشاوران حقوقی,حقوق کیفری,کارشناسی,شریف,وکیل پایه,2025-06-17 00:00:00,فعال,EMP4671,دپارتمان حقوقی قراردادها,22
1,0371555491,09108463461,09124212196,محیا بهرامی,محدثه,رستمی,خانم,محمدرضا,mbyn31@krtn.org,1983-04-01 00:00:00,...,مدیران,MBA,دکتری,UCL,معاون مدیریت,2020-09-10 00:00:00,فعال,EMP9986,مدیریت ارشد,400
2,0379935791,09124064960,09199714474,عسل سماوات,باران,جنتی,خانم,ابوالفضل,zhrkhmly@yrn.ir,1964-06-25 00:00:00,...,ستادی,مدیریت,کارشناسی ارشد,الزهرا,کارشناس اداری ارشد,1991-03-24 00:00:00,فعال,EMP3232,اداری و پشتیبانی,194
3,0385320373,09105997815,09196301994,سرکار خانم دکتر آيدا نامور,نرگس,هنری,خانم,رضا,atn96@tyn.com,1991-08-31 00:00:00,...,وکلا و مشاوران حقوقی,حقوق عمومی,کارشناسی ارشد,sorbonne,کارشناس قرارداد ارشد,2019-09-14 00:00:00,فعال,EMP2984,دپارتمان حقوقی قراردادها,29
4,0376344718,09109922504,09199348745,رها جلالی,ستايش,تهرانی,خانم,رضا,mhmd-pwraryn@grdbf.org,1982-02-23 00:00:00,...,ستادی,مدیریت,کارشناسی ارشد,تهران,کارشناس اداری ارشد,2023-02-14 00:00:00,فعال,EMP9217,اداری و پشتیبانی,199
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
396,0375063404,09106650597,09194591572,باران هدایت,حسين,شادروان,آقا,پارسا,ddfrnznyn-zhr@rwgn.net,1980-05-10 00:00:00,...,وکلا و مشاوران حقوقی,حقوق بین‌الملل,دکتری,sorbonne,وکیل ارشد,2020-07-20 00:00:00,استعفا,EMP7509,دپارتمان حقوقی قراردادها,<NA>
397,0376646756,09192868504,09124660637,الناز پویان,ایلیا,مهدیان,آقا,دانيال,hwshyrmhmdrd@shyr.ir,1987-01-31 00:00:00,...,وکلا و مشاوران حقوقی,حقوق تجارت,کارشناسی ارشد,امیرکبیر,مشاور حقوقی,2022-07-20 00:00:00,فعال,EMP5721,مشاوره حقوقی شرکتی,326
398,0385735461,09104396172,09123761033,حسام ترکاشوند,سجاد,شمشیری,آقا,عباس,frjymhdys@yrn.org,1974-07-28 00:00:00,...,وکلا و مشاوران حقوقی,حقوق تجارت,دکتری,علامه,وکیل متخصص,2007-11-18 00:00:00,فعال,EMP8608,دپارتمان حقوقی قراردادها,<NA>
399,0385976365,09126725701,09107960182,علي پارسا,حسين,سغیری,آقا,اميرمهدي,artynrwdgr@mhndsy.ir,2003-06-23 00:00:00,...,ستادی,مدیریت منابع انسانی,کارشناسی,آزاد,کارشناس منابع انسانی,2025-11-30 00:00:00,فعال,EMP7031,منابع انسانی,137
400,0362528876,091277594481,09960857522,منا محمدی,مریم,امینی خواه,خانم,حسن,amaryam6674@gmail.com,1982-07-29 00:00:00,...,مدیران,MBA,دکتری,IESE,CEO,2002-07-29 00:00:00,فعال,EMP0000,مدیریت ارشد,<NA>

In [104]:
# salary band

In [ ]:
#  performance score

In [101]:
# leave day used(for every years they worked in this holding )

In [102]:
# برای کسایی که استعفا دادن تاریخ استعفا و علت استعفاشون

In [103]:
d.info()

<class 'pandas.DataFrame'>
RangeIndex: 401 entries, 0 to 400
Data columns (total 22 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   national_code            401 non-null    str
 1   phone_number             401 non-null    str
 2   emergency_contact_phone  401 non-null    str
 3   emergency_contact_name   401 non-null    str
 4   first_name               401 non-null    str
 5   last_name                401 non-null    str
 6   gender                   401 non-null    str
 7   father_name              401 non-null    str
 8   email                    401 non-null    str
 9   birth_date               401 non-null    object
 10  marital_status           401 non-null    str
 11  address                  401 non-null    str
 12  job_group                401 non-null    str
 13  field_of_study           401 non-null    str
 14  education_level          401 non-null    str
 15  university               401 non-null    str
 16  position                 401 non-null    str
 17  hire_date                401 non-null    object
 18  employment_status        401 non-null    str
 19  employee_id              401 non-null    str
 20  department               401 non-null    str
 21  manager_id               295 non-null    Int64
dtypes: Int64(1), object(2), str(19)
memory usage: 69.4+ KB