### import libraries

In [15]:
import numpy as np, time
import pandas as pd 
from faker import Faker as fk 
import matplotlib.pyplot as plt
fake = fk("fa_IR")

### Basic personal information

In [16]:
# national_code = 03 + 7/8 + 7 ranom number
d1 = pd.DataFrame({
    "n1": "03",
    "n2": np.random.choice([7, 8], size = 85).astype(str),
    "n3": np.random.randint(1000000, 10000000, size = 85).astype(str)
})

d1["national_code"] = d1["n1"] + d1["n2"] + d1["n3"]
d1 = d1.drop(["n1", "n2", "n3"], axis=1)

# phone number = 09 + 9 random number
d1["n1"] = "09"
d1["n2"] = np.random.choice(["12", "19", "10"], size = 85)
d1["n3"] = np.random.randint(1000000, 10000000, size = 85).astype(str)
d1["phone_number"] = d1["n1"] + d1["n2"] + d1["n3"]
d1 = d1.drop(["n1", "n2", "n3"], axis=1)

# emergency contact   phone + name
d1["n1"] = "09"
d1["n2"] = np.random.choice(["12", "19", "10"], size = 85)
d1["n3"] = np.random.randint(1000000, 10000000, size = 85).astype(str)
d1_ecn = [{
    "emergency_contact_name": fake.name()
}
    for _ in range(85)]
d1["emergency_contact_phone"] = d1["n1"] + d1["n2"] + d1["n3"]
d1 = d1.drop(["n1", "n2", "n3"], axis=1)
    
d1_1 = pd.DataFrame(d1_ecn)
d1 = pd.concat([d1, d1_1], axis=1)
d1

,national_code,phone_number,emergency_contact_phone,emergency_contact_name
0,0372230741,09197131319,09128977497,هانيه ابوطالبی
1,0383707806,09122862956,09197777580,عسل ایروانی
2,0382130351,09197106474,09198709786,مبینا رضا زاده
3,0381913728,09197940986,09122045730,جناب آقای دکتر طاها همدانی
4,0372032143,09102950196,09127533473,الناز جهانی
...,...,...,...,...
80,0384328555,09105486013,09197502266,الينا نوروزی
81,0374171625,09126715977,09107781779,جناب آقای حسين تهرانی
82,0382224874,09129059021,09108984079,عرفان نوری
83,0378060925,09199488675,09193452413,سرکار خانم دکتر پرنيا موحد
84,0383741665,09195886378,09106292017,متین زارع

In [17]:
# first name
# last name
# father name
# gender
d2_f = [{
    "first_name": fake.first_name_female(),
    "last_name": fake.last_name(),
    "gender": "خانم",
    "father_name": fake.first_name_male(),
    "email": fake.company_email()
}
    for _ in range(30)]
d2_m = [{
    "first_name": fake.first_name_male(),
    "last_name": fake.last_name(),
    "gender": "آقا",
    "father_name": fake.first_name_male(),
    "email": fake.company_email()
}
    for _ in range(55)]
d2 = d2_f + d2_m
d2 = pd.DataFrame(d2)
d2

   first_name last_name gender father_name                 email
0      ياسمين      حسنی   خانم         علي    mwswyard@twlydy.ir
1        نرگس  سرخوشیان   خانم    محمدامين    bnymynzyzy@yrn.net
2        مهسا      ظفری   خانم    امیرعباس          ly01@bhr.com
3       حنانه  محمد پور   خانم   محمدپارسا  aylynshdrwn@skhrh.ir
4        اسرا     رستمی   خانم      دانیال      hwmnmhmd@grwh.ir
..        ...       ...    ...         ...                   ...
80       عباس    منصوری    آقا        حسين     lyjnylyrd@bhmn.ir
81   محمدجواد     رودگر    آقا       عرفان      zmnylnz@grwh.org
82       آریا      موحد    آقا        محمد         prs35@lwzm.ir
83      پارسا  محمد پور    آقا        عباس        rshy40@bnk.org
84     دانيال    مهدیان    آقا   محمدپارسا      xnwrwzy@ksht.com

[85 rows x 5 columns]

In [18]:
# birth date
dates = pd.date_range('1960-01-01', '2007-01-01', freq=' D')
birth_date = np.random.choice(dates, size= 10, replace= True)
d3 = pd.DataFrame(birth_date)
d3
# marital status
today = pd.Timestamp.today()

marital_status = []
for a in birth_date:
    a = (today - a).days // 365
    if a <= 22:
        marital_status.append(np.random.choice(["مجرد", "متاهل"], p= [0.95, 0.05]))
    elif a <= 27:
        marital_status.append(np.random.choice(["مجرد", "متاهل"], p= [0.6, 0.4]))
    elif a <= 35:
        marital_status.append(np.random.choice(["مجرد", "متاهل"], p= [0.3, 0.7]))
    elif a <= 50:
        marital_status.append(np.random.choice(["مجرد", "متاهل"], p= [0.15, 0.85]))
    else:
        marital_status.append(np.random.choice(["مجرد", "متاهل"], p= [0.1, 0.9]))
        
d3["marital_status"] = marital_status

d3

           0 marital_status
0 1970-07-21           مجرد
1 1975-09-14          متاهل
2 1979-02-27          متاهل
3 1969-06-09          متاهل
4 1971-03-05          متاهل
5 1968-07-03          متاهل
6 2004-11-15           مجرد
7 1984-05-14          متاهل
8 1968-12-13          متاهل
9 1970-10-20          متاهل

In [19]:
# national photo

In [20]:
# address
d4 = [{
    "address": fake.street_address(),
}
    for _ in range(85)]
d4 = pd.DataFrame(d4)
d4

                             address
0                      1080 محدثه پل
1           4835 قاضی میدان واحد 447
2                76175 نرگس بزرگ راه
3        982 محمدرضا میدان سوئیت 457
4                  72381 هانيه جزیره
..                               ...
80                  17643 هنری تقاطع
81                   181 هلیا بن بست
82                85458 محمدرضا تونل
83                   1859 یسنا میدان
84  21230 امیرحسین چهار راه واحد 927

[85 rows x 1 columns]

In [ ]:
# Job category
job_category_kind = ["وکلا و مشاوران حقوقی", "پشتیبانی حقوقی", "ستادی", "مدیران"]
d3["job_category"] = np.random.choice(job_category_kind, p= [0.45, 0.2, 0.2, 0.15])


# field of study
field = []
for a in d3["job_category"]:
    a = (today - a).days // 365
    if a == "وکلا و مشاوران حقوقی":
        field.append(np.random.choice(["حقوق خصوصی", "حقوق عمومی", "حقوق تجارت", "حقوق بین‌الملل", "حقوق کیفری"]))
    elif a == "پشتیبانی حقوقی":
        field.append(np.random.choice(["حقوق", "مدیریت", "علوم اداری", "حقوق خصوصی"]))
    elif a == "ستادی":
        field.append(np.random.choice(["مدیریت", "حسابداری", "مهندسی کامپیوتر", "مدیریت منابع انسانی", "روابط عمومی"]))
    else:
        field.append(np.random.choice(["حقوق", "MBA", "مدیریت", "حقوق تجارت"]))
        
d3["education_field"] = pd.DataFrame(field)


# education level
education_level = []
for a in birth_date:
    a = (today - a).days // 365
    if a >= 35:
        if a == "وکلا و مشاوران حقوقی":
            education_level.append(np.random.choice(["دکتری", "کارشناسی ارشد", "کارشناسی"], p= [0.3, 0.65, 0.05]))
        elif a == "پشتیبانی حقوقی":
            education_level.append(np.random.choice(["کارشناسی ارشد", "کارشناسی"], p= [0.5, 0.5]))
        elif a == "ستادی":
            education_level.append(np.random.choice(["دکتری", "کارشناسی ارشد", "کارشناسی"], p= [0.25, 0.45, 0.3]))
        else:
            education_level.append(np.random.choice(["دکتری", "کارشناسی ارشد", "کارشناسی"], p= [0.4, 0.5, 0.1]))
    elif a < 35 & a >= 28:
        if a == "وکلا و مشاوران حقوقی":
            education_level.append(np.random.choice(["دکتری", "کارشناسی ارشد", "کارشناسی"], p= [0.3, 0.6, 0.1]))
        elif a == "پشتیبانی حقوقی":
            education_level.append(np.random.choice(["کارشناسی ارشد", "کارشناسی"], p= [0.3, 0.7]))
        elif a == "ستادی":
            education_level.append(np.random.choice(["دکتری", "کارشناسی ارشد", "کارشناسی"], p= [0.15, 0.35, 0.5]))
        else:
            education_level.append(np.random.choice(["دکتری", "کارشناسی ارشد", "کارشناسی"], p= [0.3, 0.5, 0.2]))
    elif a < 28 & a >= 24:
        if a == "وکلا و مشاوران حقوقی":
            education_level.append(np.random.choice(["دکتری", "کارشناسی ارشد", "کارشناسی"], p= [0.05, 0.65, 0.3]))
        elif a == "پشتیبانی حقوقی":
            education_level.append(np.random.choice(["کارشناسی ارشد", "کارشناسی"], p= [0.3, 0.7]))
        elif a == "ستادی":
            education_level.append(np.random.choice(["کارشناسی ارشد", "کارشناسی"], p= [0.35, 0.65]))
        else:
            education_level.append(np.random.choice(["دکتری", "کارشناسی ارشد", "کارشناسی"], p= [0.05, 0.7, 0.25]))
    else:
        if a == "وکلا و مشاوران حقوقی":
            education_level.append(np.random.choice(["کارشناسی ارشد", "کارشناسی"], p= [0.1, 0.9]))
        elif a == "پشتیبانی حقوقی":
            education_level.append(np.random.choice(["کارشناسی ارشد", "کارشناسی"], p= [0.05, 0.95]))
        elif a == "ستادی":
            education_level.append(np.random.choice(["کارشناسی ارشد", "کارشناسی", "دیپلم"], p= [0.01, 0.79, 0.2]))
        else:
            education_level.append(np.random.choice(["کارشناسی ارشد", "کارشناسی"], p= [0.2, 0.8]))

d3["education_level"] = education_level

# university

TypeError: unsupported operand type(s) for -: 'Timestamp' and 'numpy.str_'

### Employment and Organizational Information