### import libraries

In [1]:
import numpy as np, time
import pandas as pd 
from faker import Faker as fk 
import matplotlib.pyplot as plt
fake = fk("fa_IR")

### Basic personal information

In [2]:
# national_code = 03 + 7/8 + 7 ranom number
d1 = pd.DataFrame({
    "n1": "03",
    "n2": np.random.choice([7, 8], size = 85).astype(str),
    "n3": np.random.randint(1000000, 10000000, size = 85).astype(str)
})

d1["national_code"] = d1["n1"] + d1["n2"] + d1["n3"]
d1 = d1.drop(["n1", "n2", "n3"], axis=1)

# phone number = 09 + 9 random number
d1["n1"] = "09"
d1["n2"] = np.random.choice(["12", "19", "10"], size = 85)
d1["n3"] = np.random.randint(1000000, 10000000, size = 85).astype(str)
d1["phone_number"] = d1["n1"] + d1["n2"] + d1["n3"]
d1 = d1.drop(["n1", "n2", "n3"], axis=1)

# emergency contact   phone + name
d1["n1"] = "09"
d1["n2"] = np.random.choice(["12", "19", "10"], size = 85)
d1["n3"] = np.random.randint(1000000, 10000000, size = 85).astype(str)
d1_ecn = [{
    "emergency_contact_name": fake.name()
}
    for _ in range(85)]
d1["emergency_contact_phone"] = d1["n1"] + d1["n2"] + d1["n3"]
d1 = d1.drop(["n1", "n2", "n3"], axis=1)
    
d1_1 = pd.DataFrame(d1_ecn)
d1 = pd.concat([d1, d1_1], axis=1)
d1

,national_code,phone_number,emergency_contact_phone,emergency_contact_name
0,0389753429,09192610310,09107476021,محمد مهدی حمیدی
1,0388956211,09194001744,09197372625,اميرمحمد مجتبوی
2,0372160637,09107052197,09101390947,محمدیاسین هاشمی
3,0373989830,09105331961,09128913416,هستي نامور
4,0386859414,09129614569,09101262823,فاطمياسارينا ظفری
...,...,...,...,...
80,0387917176,09104391661,09103867172,مهسا عبدالمالکی
81,0383915144,09101680330,09193665189,یسنا منصوری
82,0384448744,09194826462,09109819012,هانيه گلپایگانی
83,0376655431,09122170486,09198649622,کيان مهدیان
84,0381324694,09124484341,09193958280,جناب آقای دکتر پرهام ظفری

In [3]:
# first name
# last name
# father name
# gender
d2_f = [{
    "first_name": fake.first_name_female(),
    "last_name": fake.last_name(),
    "gender": "خانم",
    "father_name": fake.first_name_male(),
    "email": fake.company_email()
}
    for _ in range(30)]
d2_m = [{
    "first_name": fake.first_name_male(),
    "last_name": fake.last_name(),
    "gender": "آقا",
    "father_name": fake.first_name_male(),
    "email": fake.company_email()
}
    for _ in range(55)]
d2 = d2_f + d2_m
d2 = pd.DataFrame(d2)
d2

   first_name last_name gender father_name                    email
0        یلدا      معین   خانم     محمدعلي             aw27@syp.com
1       حنانه   علیجانی   خانم    محمدحسين     ddfrnyysh@twlydy.com
2         عسل  ترکاشوند   خانم       آرمین         lnz12@twlydy.com
3        نرگس      قاضی   خانم     محمدرضا     mhjwbmhmdmhdy@prs.ir
4        النا    سماوات   خانم        متين       aynzwthq@plysh.com
..        ...       ...    ...         ...                      ...
80  محمد مهدی     طلوعی    آقا       عرشیا  slmyrdmdy@bnydbrndz.org
81       حسام    تنزیلی    آقا   محمدياسين         zynbjhny@ndy.org
82        رضا  محمد پور    آقا         علي        rqyhmwswy@symn.ir
83   محمدحسین  محمد پور    آقا       احسان        nhdyt@rysndgy.net
84       مهدی     سغیری    آقا        يوسف           jzmny@snty.net

[85 rows x 5 columns]

In [4]:
# birth date
dates = pd.date_range('1960-01-01', '2007-01-01', freq=' D')
birth_date = np.random.choice(dates, size= 10, replace= True)
d3 = pd.DataFrame(birth_date)
# marital status
today = pd.Timestamp.today()

marital_status = []
for a in birth_date:
    a = (today - a).days // 365
    if a <= 22:
        marital_status.append(np.random.choice(["مجرد", "متاهل"], p= [0.95, 0.05]))
    elif a <= 27:
        marital_status.append(np.random.choice(["مجرد", "متاهل"], p= [0.6, 0.4]))
    elif a <= 35:
        marital_status.append(np.random.choice(["مجرد", "متاهل"], p= [0.3, 0.7]))
    elif a <= 50:
        marital_status.append(np.random.choice(["مجرد", "متاهل"], p= [0.15, 0.85]))
    else:
        marital_status.append(np.random.choice(["مجرد", "متاهل"], p= [0.1, 0.9]))
        
d3["marital_status"] = marital_status
d3.rename(columns= { 0: "birth_date"}, inplace=True)
d3

  birth_date marital_status
0 1997-09-06           مجرد
1 1987-09-07          متاهل
2 1985-09-02          متاهل
3 1979-08-26          متاهل
4 1974-01-16          متاهل
5 2001-01-05           مجرد
6 1966-07-11          متاهل
7 1990-03-15          متاهل
8 1966-06-15          متاهل
9 1962-08-07          متاهل

In [5]:
# national photo

In [6]:
# address
d4 = [{
    "address": fake.street_address(),
}
    for _ in range(85)]
d4 = pd.DataFrame(d4)
d4

                           address
0      1079 مجتهدی تقاطع سوئیت 411
1      292 رودگر آزاد راه واحد 120
2     3453 لاچینی بن بست سوئیت 297
3      610 بنیامین میدان سوئیت 846
4               939 عرفان چهار راه
..                             ...
80                99341 باران کوچه
81       9373 حمیدی بلوار واحد 821
82        2860 طاها جزیره واحد 140
83    2201 نامور بزرگ راه واحد 271
84  98583 محمد مهدی بلوار واحد 956

[85 rows x 1 columns]

In [ ]:
# Job group
job_group_kind = ["وکلا و مشاوران حقوقی", "پشتیبانی حقوقی", "ستادی", "مدیران"]
d3["job_group"] = np.random.choice(job_group_kind, p= [0.45, 0.2, 0.2, 0.15])


# field of study
field = []
for a in d3["job_group"]:
    if a == "وکلا و مشاوران حقوقی":
        field.append(np.random.choice(["حقوق خصوصی", "حقوق عمومی", "حقوق تجارت", "حقوق بین‌الملل", "حقوق کیفری"]))
    elif a == "پشتیبانی حقوقی":
        field.append(np.random.choice(["حقوق", "مدیریت", "علوم اداری", "حقوق خصوصی"]))
    elif a == "ستادی":
        field.append(np.random.choice(["مدیریت", "حسابداری", "مهندسی کامپیوتر", "مدیریت منابع انسانی", "روابط عمومی"]))
    else:
        field.append(np.random.choice(["حقوق", "MBA", "مدیریت", "حقوق تجارت"]))
        
d3["field_of_study"] = field


# education level
education_level = []
for i in range(len(d3)):
    b = d3["job_group"].iloc[i]
    a = (today - d3["birth_date"].iloc[i]).days // 365
    if a >= 35:
        if b == "وکلا و مشاوران حقوقی":
            education_level.append(np.random.choice(["دکتری", "کارشناسی ارشد", "کارشناسی"], p= [0.3, 0.65, 0.05]))
        elif b == "پشتیبانی حقوقی":
            education_level.append(np.random.choice(["دکتری", "کارشناسی ارشد", "کارشناسی"], p= [0.2, 0.5, 0.3]))
        elif b == "ستادی":
            education_level.append(np.random.choice(["دکتری", "کارشناسی ارشد", "کارشناسی"], p= [0.25, 0.45, 0.3]))
        else:
            education_level.append(np.random.choice(["دکتری", "کارشناسی ارشد", "کارشناسی"], p= [0.4, 0.5, 0.1]))
    elif (a < 35) & (a >= 28):
        if b == "وکلا و مشاوران حقوقی":
            education_level.append(np.random.choice(["دکتری", "کارشناسی ارشد", "کارشناسی"], p= [0.3, 0.6, 0.1]))
        elif b == "پشتیبانی حقوقی":
            education_level.append(np.random.choice(["کارشناسی ارشد", "کارشناسی"], p= [0.3, 0.7]))
        elif b == "ستادی":
            education_level.append(np.random.choice(["دکتری", "کارشناسی ارشد", "کارشناسی"], p= [0.15, 0.35, 0.5]))
        else:
            education_level.append(np.random.choice(["دکتری", "کارشناسی ارشد", "کارشناسی"], p= [0.3, 0.5, 0.2]))
    elif (a < 28) & (a >= 24):
        if b == "وکلا و مشاوران حقوقی":
            education_level.append(np.random.choice(["دکتری", "کارشناسی ارشد", "کارشناسی"], p= [0.05, 0.65, 0.3]))
        elif b == "پشتیبانی حقوقی":
            education_level.append(np.random.choice(["کارشناسی ارشد", "کارشناسی"], p= [0.3, 0.7]))
        elif b == "ستادی":
            education_level.append(np.random.choice(["کارشناسی ارشد", "کارشناسی"], p= [0.35, 0.65]))
        else:
            education_level.append(np.random.choice(["دکتری", "کارشناسی ارشد", "کارشناسی"], p= [0.05, 0.7, 0.25]))
    else:
        if b == "وکلا و مشاوران حقوقی":
            education_level.append(np.random.choice(["کارشناسی ارشد", "کارشناسی"], p= [0.1, 0.9]))
        elif b == "پشتیبانی حقوقی":
            education_level.append(np.random.choice(["کارشناسی ارشد", "کارشناسی"], p= [0.05, 0.95]))
        elif b == "ستادی":
            education_level.append(np.random.choice(["کارشناسی ارشد", "کارشناسی"], p= [0.21, 0.79]))
        else:
            education_level.append(np.random.choice(["کارشناسی ارشد", "کارشناسی"], p= [0.2, 0.8]))

d3["education_level"] = education_level
# university

In [ ]:
# position
position = []
for i in range(len(d3)):
    if d3["job_group"].iloc[i] == "وکلا و مشاوران حقوقی":
        if d3["education_level"].iloc[i] == "کارشناسی":
            position.append("وکیل پایه")
        elif d3["education_level"].iloc[i] == "کارشناسی ارشد":
            position.append(np.random.choice(["مشاور حقوقی", "کارشناس قرارداد ها"], p= [0.4, 0.6]))
        else:
            position.append(np.random.choice(["وکیل ارشد", "وکیل متخصص"], p= [0.6, 0.4]))
    elif d3["job_group"].iloc[i] == "پشتیبانی حقوقی":
        if d3["education_level"].iloc[i] == "کارشناسی":
            position.append("کارشناس اداری")
        elif d3["education_level"].iloc[i] == "کارشناسی ارشد":
            position.append(np.random.choice(["کارشناس اسناد", "تنظیم‌کننده پیش‌نویس"], p= [0.4, 0.6]))
        else:
            position.append("هماهنگ‌کننده جلسات")
    elif d3["job_group"].iloc[i] == "ستادی":
        if d3["education_level"].iloc[i] == "کارشناسی":
            if d3["field_of_study"].iloc[i] == "مدیریت منابع انسانی":
                position.append("کارشناس HR")
            elif d3["field_of_study"].iloc[i] == "روابط عمومی":
                position.append("کارشناس روابط عمومی")
            elif d3["field_of_study"].iloc[i] == "مهندسی کامپیوتر":
                position.append("کارشناس IT")
            elif d3["field_of_study"].iloc[i] == "حسابداری":
                position.append("کارشناس مالی")
            else:
                position.append("کارشناس")
        else:
            if d3["field_of_study"].iloc[i] == "مدیریت منابع انسانی":
                position.append("کارشناس HR ارشد")
            elif d3["field_of_study"].iloc[i] == "روابط عمومی":
                position.append("ارشد کارشناس روابط عمومی")
            elif d3["field_of_study"].iloc[i] == "مهندسی کامپیوتر":
                position.append("کارشناس IT ارشد")
            elif d3["field_of_study"].iloc[i] == "حسابداری":
                position.append("ارشد کارشناس مالی")
            else:
                position.append("کارشناس ارشد")
    else:
        if d3["education_level"].iloc[i] == "کارشناسی":
            position.append(np.random.choice(["مدیر IT", "مدیر مالی"]))
        elif d3["education_level"].iloc[i] == "کارشناسی ارشد":
            position.append(np.random.choice(["مدیر منابع انسانی", "مدیر عملیات"]))
        else:
            position.append(np.random.choice(["مدیر واحد حقوقی", "مدیر منابع انسانی"]))
        
position

[np.str_('کارشناس قرارداد ها'),
 np.str_('مشاور حقوقی'),
 np.str_('کارشناس قرارداد ها'),
 np.str_('وکیل متخصص'),
 np.str_('کارشناس قرارداد ها'),
 'وکیل پایه',
 np.str_('کارشناس قرارداد ها'),
 np.str_('مشاور حقوقی'),
 np.str_('مشاور حقوقی'),
 np.str_('وکیل ارشد')]

In [ ]:
# department (کنسل شد)

In [ ]:
# hire date

In [ ]:
# contract type

In [ ]:
# employment status

### Employment and Organizational Information